

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Intersoft.AppFramework.ModelServices;
using Intersoft.Crosslight;
using Intersoft.Crosslight.Data;
using Intersoft.Crosslight.Data.ComponentModel;
using Intersoft.Crosslight.Data.EntityModel;
using System.ComponentModel;
namespace Business.DomainModels.Inventory
{

    public partial interface ICategoryRepository : IEditableEntityRepository<Category, int>
    {
    }

    public partial class CategoryRepository : EditableEntityRepository<Category, int>, ICategoryRepository
    {
        public CategoryRepository(IEntityContainer entityContainer)
            : base(entityContainer)
        {
            this.ResourceName = "Categories";
        }
    }

    public partial interface IItemRepository : IEditableEntityRepository<Item, int>
    {
    }

    public partial class ItemRepository : EditableEntityRepository<Item, int>, IItemRepository
    {
        public ItemRepository(IEntityContainer entityContainer)
            : base(entityContainer)
        {
            this.ResourceName = "Items";
        }
    }

}
