//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DomainModels.PushNotification
{
    using System;
    using System.Collections.Generic;

    public partial class DeviceToken
    {
        public string DeviceTokenId { get; set; }
        public string OperatingSystem { get; set; }
        public string Token { get; set; }
        public string UserId { get; set; }
    }
}
